### ISSUE TITLE
Using inside of my Designer - Events not raised, Text not formated

### ISSUE THREAD

**Issue by jogibear9988** [papyrs/stylo#112]
### Expected Behavior

I should be able to formt my Text using Stylo

### Actual Behavior

I use your component inside of my WebComponentDesigner, but again once more, the vents are not raised.
I did work (fixed it long time ago), but I havend Tested it for weeks, so I don't know what is breaking it.
Do you have any Ideas? Or do I need to debug this once more (will take a long time to get back into you component, at least as I don't use React very often)

### Reproduction

Steps to reproduce the issue:

1. Go to my Designer: https://node-projects.github.io/web-component-designer-demo/index.html
2. Add following Code (in Source View):

        <span style="position:absolute;left:84px;top:90px;">
            <div style="transform-origin:50% 50%;">Test</div>
        </span>

3. Switch to Design view and Edit Text via DoubleClick

### Screenshots

![Aufnahme_2022_10_26_21_57_16_792](https://user-images.githubusercontent.com/364896/198125490-a6fdb8d2-0144-4c6e-ab64-08719ca8c7a4.gif)

### Environment

- Browser(s): Chrome 107
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by peterpeterparker** [comment]
> I use your component ... but again once more .... Or do I need to debug this once more ...

I appreciate that you use the component but just to be clear, I don't force you to use it. If you don't like it, don't use it.

That being said, if you could narrow down the issue to a particular version that would help debug because there wasn't any changes regarding events in a long time.

**Comment by jogibear9988** [comment]
> > I use your component ... but again once more .... Or do I need to debug this once more ...
> 
> I appreciate that you use the component but just to be clear, I don't force you to use it. If you don't like it, don't use it.
> 
> That being said, if you could narrow down the issue to a particular version that would help debug because there wasn't any changes regarding events in a long time.

Sorry, this shouldn't be criticism :-)

I look, I thought maybe you had a direct idea.
Could also be cause of changes on my side.

**Comment by jogibear9988** [comment]
Found the issue....
I had a global PointerDownHandler, this stops the click from being raised. Need to look how I fix this. Sorry.

**Comment by peterpeterparker** [comment]
Glad to hear that 👍
