### ISSUE TITLE
quick test on latest FF

### ISSUE THREAD

**Issue by eikaramba** [papyrs/stylo#23]
Tested on FF 96

- Links not working (i cannot open a link, only delink a text)
- when reordering images i get a duplicated image in the new and old spot.

**Comment by jeregrine** [comment]
Confirmed on 97.0 (64-bit) macOS 12.3 beta

**Comment by peterpeterparker** [comment]
Thanks! agree on both, can reproduce with FF 97 too. 

The image reordering happens in Chrome too.

**Comment by peterpeterparker** [comment]
Links:

- creating links on Firefox should now be fixed
- removing links works too however I am not able to preserve the styles (colors etc.) of the children when I do so. It works in Safari and Chrome but not in FF. Seems the selection API behaves differently on FF. I can live with it. If you want to give a try, that's the [removeLink](https://github.com/papyrs/stylo/blob/84c849c57b136751623aecaa00c9af06d1934a7b/src/utils/link.utils.ts#L11) function.
