### ISSUE TITLE
Integration of Stylo inside of other webcomponents

### ISSUE THREAD

**Issue by jogibear9988** [papyrs/stylo#39]
### Feature Description

I'm creating a designer for usage with webcomponents: https://github.com/node-projects/web-component-designer (demo: https://node-projects.github.io/web-component-designer-demo/index.html)).
Inside of this I try to include stylo as a editor of rich text content.
For this some bugs/fixes need to be made. 
I create a pull request when I got it workin, than we can discuss how to integrate the needed changes. (If you'd like to)

### Use Case

Usage of stylo inside of webcomponents and a designer

**Comment by jogibear9988** [comment]
Here is an example of my integration 👍 
https://github.com/node-projects/web-component-designer/pull/72/commits/9c335a13beb5d265139e114559a562b15b0c619f

**Comment by peterpeterparker** [comment]
Sure great idea. Did you manage to make it happen with your PR?

**Comment by jogibear9988** [comment]
With my PR (to stylo) it will work in my designer.

**Comment by jogibear9988** [comment]
I'll look to rework my pull request in the evening, and write back when I'm ready

**Comment by peterpeterparker** [comment]
Just reopen it because I am doing a couple of things to finalize it ;)

**Comment by peterpeterparker** [comment]
Get shadow or doc selection and range across the lib 👉 https://github.com/papyrs/stylo/pull/44

**Comment by peterpeterparker** [comment]
Wider safe area for toolbar 👉 #45

**Comment by peterpeterparker** [comment]
Refactor css utils 👉 #46

**Comment by peterpeterparker** [comment]
Small refactor to detect content editable 👉 #47

**Comment by peterpeterparker** [comment]
Fixed incorrect `import` ending with`.js` (in #44 too)

**Comment by peterpeterparker** [comment]
Group event information for toolbar 👉 #48

**Comment by peterpeterparker** [comment]
This has now been released in `v0.0.8`. Thanks a lot for the help and PR 🙏
