### ISSUE TITLE
Info: Demonstration usage inside of webcomponents

### ISSUE THREAD

**Issue by jogibear9988** [papyrs/stylo#49]
This is only for information:

I created a designer framework for webcomponents. Inside of it there is also the possibility to edit formated text, where I now included stylo. A demo is here: https://node-projects.github.io/web-component-designer-demo/index.html

To test drag the "div with text" form the elements panel (see lements/demo/div with text) to the designer and doubleclick it.

It's only a preview of the integration at the moment, there is still work to do (I think mainly at my designer, not here).

**Comment by peterpeterparker** [comment]
I gonna close this issue since it is an information and has been open for a while. Happy to link anyone that ask for a demo usage of the lib within wc to your project 👍
