### ISSUE TITLE
CDN link is broken

### ISSUE THREAD

**Issue by josiaho** [papyrs/stylo#51]
### Expected Behavior

The CDN url ([https://unpkg.com/@papyrs/stylo@alpha/dist/stylo/stylo.esm.js](https://unpkg.com/@papyrs/stylo@alpha/dist/stylo/stylo.esm.js)) seems to be broken.

### Screenshots
<img width="356" alt="Screen Shot 2022-02-23 at 11 23 50 AM" src="https://user-images.githubusercontent.com/1563159/155383314-b4bb9fc1-8d98-4b34-9a33-b5493992b5fd.png">

**Comment by peterpeterparker** [comment]
Yeah my bad I actually never went with "alpha" tag to npm but only regular 😅

Following is correct:

```
https://unpkg.com/@papyrs/stylo@latest/dist/stylo/stylo.esm.js
```

Where did you find the CDN url you are mentioning? Happy to fix the reference.

**Comment by josiaho** [comment]
Perfect - thanks!

I found the link in the repo README: [https://github.com/papyrs/stylo](https://github.com/papyrs/stylo)

**Comment by peterpeterparker** [comment]
Thanks. Fixed with commit d8ac043

**Comment by peterpeterparker** [comment]
what kind of project? vanilla, react, svelte, etc?
how to you import the component? `import ...` or `<script ...`?

**Comment by josiaho** [comment]
Script tag - and I just realized I didn't have the script 'type' set as 'module' 🤦🏻‍♂️. My bad - thanks!

**Comment by peterpeterparker** [comment]
Coolio if it works out
