### ISSUE TITLE
color picker overlay height on brave

### ISSUE THREAD

**Issue by peterpeterparker** [papyrs/stylo#63]
### Expected Behavior

See screenshot, the color picker is not properly sized if used in Brave.

<img width="1074" alt="Capture d’écran 2022-04-09 à 13 18 16" src="https://user-images.githubusercontent.com/16886711/162569567-53413130-f49f-4a36-b4f0-47352b226be3.png">

**Comment by zRains** [comment]
https://github.com/papyrs/stylo/blob/f0914f9c4efb38b019426d77bb6fe86078a2723e/src/components/toolbars/toolbar/toolbar/toolbar.scss#L47-L51

```scss
height: unset;
```

I always thought it was no bug XD, and this is my solution.

**Comment by peterpeterparker** [comment]
> I always thought it was no bug XD

Haha it's in beta, you can expect it's a bug 😉

Thanks for the solution, it works out! Also fixed Safari at the same time.
