### ISSUE TITLE
Colors don't close

### ISSUE THREAD

**Issue by viraladmin** [papyrs/stylo#81]
I don't think this is the same issue as being discussed on the other thread, but if it is feel free to close. I notice nothing short of a right click closes the color box modal when its opened.

To reproduce visit https://stylojs.com/, highlight text, select the color tool, change the color of text. The modal does not close. Click elsewhere on the page, the modal does not close. Start typing again in the editor and still the modal does not close. right click and the modal now closes.

Again, this is above my ability but I have been trying to figure out where to place the code cause I think I know the solution. 

In my mind the modal should be closed upon one of three events. 

1. User clicking button to select color
2. onkeyup event of the input box if input.length == 7 (pound sign + 6 numbers) 
3. user pressing esc key to close box

**Comment by viraladmin** [comment]
So far I have the following:

Line :104 and 111 on `src/components/color/color/color.tsx`

I added `document.querySelector('stylo-toolbar').shadowRoot.querySelector('.tools').classList.remove('tools-activated');`

![image](https://user-images.githubusercontent.com/22060035/168443214-885dc22b-2a31-4d0b-9275-cfd99e9b7696.png)

![image](https://user-images.githubusercontent.com/22060035/168443223-3628d861-bb49-43f1-9592-0f372826b1f5.png)

This closes the color toolbox, but it does not reset the other tools - which still only happens when right clicking. I have not figured out how to reset the toolbar.

Any suggestions would be great.

**Comment by peterpeterparker** [comment]
Thanks for the issue. Solved in #82.
