### ISSUE TITLE
When typing Japanese, line breaks are automatically inserted.

### ISSUE THREAD

**Issue by HWRDWLWZ** [papyrs/stylo#83]
### Expected Behavior

When Japanese is converted from hiragana to kanji and the enter key is pressed, the character is confirmed and the rest of the sentence can be entered.

### Actual Behavior

Pressing the enter key to convert from hiragana to kanji automatically breaks the line.

### Reproduction

Steps to reproduce the issue:

1.Type Hiragana
2.Convert to Kanji with Space key
3.Fix the word with Enter key

### Screenshots

https://user-images.githubusercontent.com/86988898/168548606-910c5b11-01ea-44a2-a82d-32ce9919dd33.mov

### Environment

- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):
-MacBook Pro (13-inch, M1, 2020) mac OS Big Sur 11.6.1（20G224）
※I've tried with Android(Pixel6), It didn't reappear, no problem.

**Comment by peterpeterparker** [comment]
@HWRDWLWZ is following a particular plugin or it uses a feature of the browser?
if native, what browser and what OS?

the error happens when you press space right?
can you give me a list of keys that can lead to the issue?

i tried to reproduce the issue with chrome and the [chrome input tools](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab) but wasn't able to reproduce it.

thanks in advance for the details

<img width="800" alt="Capture d’écran 2022-05-16 à 20 33 18" src="https://user-images.githubusercontent.com/16886711/168659647-1e203276-2bb4-41c1-bbb8-15d445daea34.png">

**Comment by HWRDWLWZ** [comment]
Browser is google chrome.

The issue is the create New line happens when typed Enterkey.

(in video, I found another issue that is word goes duplicate automatically when type word because of word suggest in Mac native function.)

**Comment by peterpeterparker** [comment]
Which Chrome version? 
Windows or Mac?

As you can see in following capture, I write gibberish but enter key is working with the Google Inputs tool.

I need to find a way to replicate the same settings as you have and try to see why it propagate the "enter" event.

For some reason in your setting the enter keys of the type assist are bubbling to the content editable - i.e. are catched here https://github.com/papyrs/stylo/blob/1b283a43a97a2717a4925320320165147dd01e46/src/events/enter.events.ts#L31

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/16886711/168853680-5199cebe-d873-4d28-bc02-b19f6696b1a3.gif)

**Comment by peterpeterparker** [comment]
I've tried again, still no luck. What version of Chrome are you using?

also look like the Google inputtool I'm using doesn't look exactly the same as the one in above video so maybe something different there that does not help reproducing the issue.

Long story short, if someone who speak japanese can help debugging this, it would be helpful!

**Comment by peterpeterparker** [comment]
@hideto0118 will give a hand debugging this. I'll prepare a branch with some debugging information and hideto0118 will try to reproduce the error and collect some info

**Comment by peterpeterparker** [comment]
> Pressing the enter key to convert from hiragana to kanji automatically breaks the line.

Are you pressing "enter" only or are you pressing "shift + enter" or another combination?

**Comment by peterpeterparker** [comment]
In OpenChat they have implemented a feature "Enter key sends message" for the same reason I think. I'll try to see what they implemented.

**Comment by peterpeterparker** [comment]
We should try https://github.com/ckeditor/ckeditor5/issues/5750#issuecomment-555375186

**Comment by peterpeterparker** [comment]
I deployed a potential fix, can you give it a try @HWRDWLWZ and let me know if it works out (🤞)?

**Comment by HWRDWLWZ** [comment]
It work!! Thank you!

https://user-images.githubusercontent.com/86988898/172050356-135d4552-3a3a-4745-82f0-37ee462c3fef.mov

**Comment by peterpeterparker** [comment]
Yoohoo! I'm so happy to hear that 🥳.

It was tricky to understand what was going wrong on and did not knew about the `keyCode 229`.

Thanks a lot for the help and feedback @HWRDWLWZ 🙏
